### ISSUE TITLE
Date au format américain - remplacer par champ texte ?

### ISSUE THREAD

**Issue by ElieDeloumeau** [vikbez/covid-sortie#1]
La date de rendu est au format américain, ça peut poser problème ?

**Comment by vikbez** [comment]
Je pense pas que ça pose de soucis (pour info le format est pas americain mais [RFC3339](https://www.w3.org/TR/2011/WD-html-markup-20110405/input.date.html)).
C'est le plus compatible (code le plus simple qui marche partout).
Si il y a des soucis comme ça j'aviserais.

**Comment by FirelightFlagboy** [comment]
the date here manage on the navigator side if you use `<input type="date" >`

**Comment by ro-olivier** [comment]
C'est le navigateur (et éventuellement la langue de l'OS) qui pilote le format de la date.
@ElieDeloumeau en modifiant le paramétrage de votre navigateur (par exemple l'option "Langue" dans Firefox) vous devriez pouvoir faire passer la date sur un format standard).

It's the browser (or, in some cases, the OS language options) that's responsible for the date format.
You should be able to change the date format to something more standard by changing your browser settings (in Firefox it's in the Language settings).

**Comment by greg3z** [comment]
Egalement coincé par le format de la date et je ne pense pas rebasculer mon browser en FR pour ça. Vu que c'est en usage en France uniquement, ça pourrait valoir le coup de forcer le format.

Sinon super idée, merci ! ;)

**Comment by vikbez** [comment]
Je vais sans doute remplacer par un champ texte simple
Votre avis ?
