### ISSUE TITLE
Amélioration 

### ISSUE THREAD

**Issue by Kev316643** [vikbez/covid-sortie#10]
Bonjour, déjà merci beaucoup pour le partage ! Juste pour améliorer si jamais vous le pouvez lorsque l'on ouvre avec Google Chrome tout marche nickel, juste le petit encadré pour la signature n'est pas positionné comme il faut quand on signe avec le doit (sur mobile) la signature se fait beaucoup plus au dessus.... Voilà merci encore !

**Comment by vikbez** [comment]
Retestez je viens de faire une mise a jour ?
