### ISSUE TITLE
date de naissance

### ISSUE THREAD

**Issue by baumedutigrrr** [vikbez/covid-sortie#11]
Bonjour, 
Merci bcp pour cet outil très pratique, toutefois, impossible de rentrer ma date de naissance sur portable parce que cela implique de remonter mois par mois jusqu'à celle-ci. Est ce que l'alternative pourrait être de rentrer textuellement la date de naissance ? 
Merci,
Baume

**Comment by ALiagre** [comment]
> 
> 
> Bonjour,
> Merci bcp pour cet outil très pratique, toutefois, impossible de rentrer ma date de naissance sur portable parce que cela implique de remonter mois par mois jusqu'à celle-ci. Est ce que l'alternative pourrait être de rentrer textuellement la date de naissance ?
> Merci,
> Baume

+1. Inutilisable sur smartphone s'il n'est pas possible d'éditer directement la date de naissance. Vous pouvez l'indiquer uniquement en champs texte plutôt que date ?

**Comment by nheir** [comment]
Symptome: pas possible de changer directement l'année (ça dépend des navigateurs)
![image](https://user-images.githubusercontent.com/2434994/76943789-38ad0100-6900-11ea-882c-5f6339bc3b10.png)

sur d'autres
![image](https://user-images.githubusercontent.com/2434994/76943953-7873e880-6900-11ea-9d25-850efc998ba0.png)

**Comment by vikbez** [comment]
voir #1
