### ISSUE TITLE
Héberger sur gh-pages

### ISSUE THREAD

**Issue by guillaumepotier** [vikbez/covid-sortie#18]
Hello,

Tout d'abord merci pour ce projet fort utile quand on a fait ni stock de pâtes, PQ, cartouches d'encre ;)

J'ai découvert le projet sur FB car plein de gens criaient au fake, usurpation d'identité et cie.. Je pense que le domaine vik.io n'est pas des plus rassurants. Puisqu'il y a 0 serveur, pourquoi ne pas l'hoster directed sur Github Pages ? Et mettre plus en avant le fait que c'est open source, hosté par github ? (on peut toujours craindre une modification du code entre le repo et le hosting vik.io).

Bref, j'essaye de rassurer en disant que c'est clean, pratique, et sauve des arbres, mais un meilleur "branding" pourrait plus aider à diffuser le projet.

Take care

**Comment by KrustyHack** [comment]
Ay,

Mince, tu m'as pris de vitesse ! J'allais justement proposer à @vikbez de l'héberger sur du S3. :)

**Comment by Francescu** [comment]
Le plus étonnant c’est qu’il y a un GH pages avec un redirect plutôt que le code 🤔

**Comment by vikbez** [comment]
Alors; 
c'etait hosté sur gh-pages au debut mais l'url ne rassurait pas nonplus donc je prefere garder une version "url courte".
Les gens ont **vraiment** peur pour leur données (je recois plein de mail pour avoir des infos).
Il y a deja des generateurs qui ont des domaines avec url "propres";
Donc je pense que celui ci va rester comme ça.

Apres c'est open source rien n'empeche de repliquer ça ailleurs si vous voulez :)

**Comment by Francescu** [comment]
@vikbez très compréhensible, et merci pour le travail fournit. En revanche contrairement à ce qu’affirme le Readme, l’ami développeur ne peut donc pas valider. 

Pourquoi ne pas laisser les deux urls ? Le GH pages qui peut être trusté par les devs et l’URL courte également (mais je ne comprend pas, c’est un .io, pas un .fr que les gens trusteraient un peu plus)

**Comment by pmithrandir** [comment]
De plus, je mettrais l'url officielle dans le readme github. avec la liste des url autorisée en mirroir.
Parce que la, tu risques d'avoir des gens qui récupère le projet, le font passer pour le leur et l'héberge pour en tirer des bénéfices. 
ton code est clean sur github, mais quid de celui qu'ils exposent ?

exemple, j'ai trouvé ton code sur picta.fr, est ce toi, ou quelqu'un qui essaye de se faire connaitre, ou un généreux donateur de bande passante, on ne sait pas.

Par ailleurs, ce genre de site est parfait pour un usage S3 + cloud front.(ou équivalent)

**Comment by Francescu** [comment]
Pour clarifier pour tous ceux qui liraient ça: pour le moment https://vik.io/sortie est entièrement clean. GitHub Pages permettrait juste d'être sûr que le code ici et le code sur le site soient identiques, même en cas de "piratage" du site. 

Je vais personnellement setup un miroir pour ma famille et mes proches.

**Comment by vikbez** [comment]
Je vais refaire une release gh-pages

la suite dans #23  pour le readme merci

**Comment by vikbez** [comment]
up
https://vikbez.github.io/covid-sortie/

**Comment by guillaumepotier** [comment]
Excellent, j'ai [tweeté](https://twitter.com/guillaumepotier/status/1240215739673579520) :)
