### ISSUE TITLE
Site déclaré sur Signal-arnaques ...

### ISSUE THREAD

**Issue by GDeb59** [vikbez/covid-sortie#19]
Hello,

Bravo pour l'initiative mais tout le monde a peur du phishing en saisissant ses données personnelles et du coup le site a été déclaré par quelqu'un sur : https://www.signal-arnaques.com/scam/view/213801

C'est nul, ça partait d'une bonne intention ... 

Alors que le code html est disponible ... pour les initiés. Cette page html est plutôt bien pratique.

**Comment by vikbez** [comment]
voir #20
