### ISSUE TITLE
Aidez moi pour les infos en footer / rassurer les gens.

### ISSUE THREAD

**Issue by vikbez** [vikbez/covid-sortie#20]
J'ai **beaucoup** de demandes type "comment je suis sur que vous volez pas mes infos"

Si vous pouviez m'aider a rediger un texte propre a mettre en footer / ou une page pour expliquer aux gens pourquoi on ne recupere pas de donnees ça serait top;

**Comment by PierrickP** [comment]
Bravo pour le boulot.
Ce que tu peux leur proposer c'est de l'utiliser en offline.
Ils leur suffit de faire "enregistrer la page sous...", ce mettre en mode avion et ouvrir le fichier.

**Comment by vikbez** [comment]
Oui, mais le probleme est que toutes categories de gens utilisent ce site; (et beaucoup de tres novices) ils ne comprennent pas cette explication !

**Comment by KrustyHack** [comment]
Ay,

Ca me fait rire quand même parce que pour ce genre de service "gratuit" les gens sont tout fou quand à leurs données personnelles. Par contre quand ils utilisent Facebook et autres sites ou apps mobiles type pompe à données y a plus personne.

Sérieusement, tu peux mettre le footer que tu veux les gens seront toujours pareil. A la limite met des mentions légales pour que les gens puissent t'identifier comme une entité réelle.

Ou alors créé une app Facebook, comme ça ils auront moins peur...

**Comment by guillaumepotier** [comment]
Je pense que malheureusement le mieux serait:

- de le faire héberger par un site / une url de confiance
- le faire valider/lister sur un site de l'état ou autre

Tu auras beau mettre/expliquer ce que tu veux, les gens se méfieront toujours (et je trouve ça bien, cette sensibilité sur les informations perso et identité!)

**Comment by vikbez** [comment]
Oui ça m'a etonné en bien aussi que les gens demandent autant; 
Par contre vu le nombre de visiteurs uniques c'est pas si enorme finalement si on fait en pourcentage 😆 

Bon je vais ameliorer un peu le footer et voila

**Comment by KrustyHack** [comment]
> Tu auras beau mettre/expliquer ce que tu veux, les gens se méfieront toujours (et je trouve ça bien, cette sensibilité sur les informations perso et identité!)

Je trouve ça bien aussi que les gens se soucient de leurs infos, mais quand à côté ils téléchargent des apps bidons ou partagent tout à la terre entière via des sites ça me rend dingue quand quelqu'un comme @vikbez offre un service honorable pour aider et que les gens crient au scandale pour leur données. pour moi c'est de l’hypocrisie.

Bref il fallait que je le lâche un peu, ça fait du bien. Revenons au sujet, je me suis égaré. :p

Comme l'a dit @guillaumepotier le faire lister par une entité officielle serait clairement la solution. Ou une url propre. Avec des mentions légales.

Perso je ne vois pas d'autres solutions là tout de suite.

**Comment by GDeb59** [comment]
@vikbez j'ai vu un post FB d'une gendarmerie qui postait ton lien pour ceux qui n'ont pas d'imprimante.

Le problème est que d'autres s'en sont inspirés et se sont dit : "Tiens c'est l'occaz de choper un max de données perso" et potentiellement peuvent faire du phishing ...

A part faire héberger la page sur un site d'état ... je ne vois pas trop d'autres solutions.

**Comment by vikbez** [comment]
J'ai rajouté un peu d'infos;
Et oui si tu retrouves le post ça serait parfait je pourrais le linker en bas de page
Effectivement hier les sites "seo first" ont fleuri ...

**Comment by pmithrandir** [comment]
Bonjour,
pourquoi ne pas le mettre en header ce message ?
Je ne pense pas que la plupart lise jusqu'au bout.

Autrement, des label comme "open source, RGPD compatible(déjà présent) peuvent rassurer.

Bonne initiative en tout cas.
pierre

**Comment by renaudwangler** [comment]
Une idée simple : expliquer comment enregistrer le .html sur son ordi/tablette. le traitement purement local peut rassurer non ?

**Comment by seyratstyle** [comment]
Bien joué pour l'initiative romain, 
Plusieurs de mes amis avons utilisé cette adresse : https://picta.fr/covid/
Parce que du coup, comme ton footer est pas actualisé sur celle là on se poste la question si c'est un pas un phishing 😏

**Comment by GregOriol** [comment]
Le message actuel mal formulé et parler de "RGPD" réveille le côté anxiogène.

Il faudrait indiquer que la page est uniquement affichée sur le navigateur, qu'aucun traitement n'est effectué par vous et à aucun moment les données ne sont transmises à quiconque.

Le renvoi vers le code source doit être séparé, car info technique pour des initiés.

**Comment by rambobinator** [comment]
Hello,
Merci beaucoup pour l'outil, je rejoins  guillaumepotier ça à beau être du plain html, l'url peut rebuter. Pourquoi ne pas juste host avec github pages ?

**Comment by pmithrandir** [comment]
l'url publique officielle : https://vikbez.github.io/covid-sortie/

Moi je garderai le lien github, parce que c'est vraiment ca qui m'a rassuré.

La formulation en revanche est moyenne.

Conforme RGPD, n'utilise ni stockage ni cookies ! Fonctionne hors ligne.
Code et un peu plus d'infos dispo sur github.com
Créé par Romain Gay pour moi même et mes amis à la base, désolé du site moche c'etait pas censé avoir autant de succes !

> Site créé par Romain Gay.
> J'ai eu cette initiative pour aider mon entourage et j'ai décidé de la partager auprès de la communauté.
> Ce site est exécuté sur votre navigateur uniquement et je ne collecte aucune information.
> Le code source est disponible sur github.com

**Comment by nheir** [comment]
Apparemment, il faudra dorénavant avoir une version physique de l'attestation, limitant l'intérêt des générateurs d'attestation (sinon pour l'entête).

https://www.bfmtv.com/tech/confinement-finalement-l-attestation-sur-smartphone-ne-suffit-pas-1877104.html

**Comment by vikbez** [comment]
Merci pour la formularion j'ai maj le footer, effectivement j'ai mis le lien de l'article aussi en warning
