### ISSUE TITLE
Lister liens "ok" connus pour ajouter dans le readme

### ISSUE THREAD

**Issue by vikbez** [vikbez/covid-sortie#23]
comme vu dans #18 

pouvez vous m'aider a lister les sites alternatifs sûrs pour ajouter au readme ?

Merci

**Comment by pmithrandir** [comment]
J'ai oublié de dire, il ne faut pas non plus que ces sites changent ton code après coup.
Github page semble donc une très bonne idée.(de ce que je comprends, le code exposé est "garanti" identique au code source dans le repo.

**Comment by brnltn** [comment]
Je l'ai mis sur le mien ici http://brunoloton.com/covid-sortie/ pour le communiquer à mon entourage, je n'ai pas touché au code. Je n'avais pas vu qu'il avait été publié sur Github page ce qui me semble être une très bonne option 👍

**Comment by brnltn** [comment]
Cependant il semblerait que l'attestation présentée en format numérique ne soit plus autorisée, attente de confirmation dans la journée https://twitter.com/Numerama/status/1240218721324589057

**Comment by GregOriol** [comment]
Un des problèmes majeurs avec le smartphone est que si on affiche le document en entier sur l'écran, le texte est trop petit pour être lisible, on ne peut voir ni les infos dans les champs ni la case qui a été cochée. Il n'est absolument pas envisageable pour les agents qui contrôleront de toucher l'écran, il faudrait donc que l'utilisateur zoom/scroll sur les différents endroits importants du document, ça complexifie énormément le traitement vs une feuille de papier.

Si on pouvait s'affranchir de la mise en page et passer sur un vrai format numérique adapté au mobile, ça faciliterait beaucoup les choses; peut-être via une app/webapp officielle du gouvernement ?

**Comment by brnltn** [comment]
C'est officiel, présenter une attestation numérique sur un écran n'est pas valable aux yeux des autorités https://www.bfmtv.com/tech/confinement-finalement-l-attestation-sur-smartphone-ne-suffit-pas-1877104.html Je pense que le mieux pour éviter que des personnes tombent dessus sans savoir leur risque s'ils ne l'impriment pas est d'ajouter un message très voyant expliquant qu'ils doivent absolument l'imprimer. Ou retirer ce service de nos serveurs.

**Comment by vikbez** [comment]
Done info + warning

**Comment by vikbez** [comment]
Site fermé, je close l'issue
