### ISSUE TITLE
Finalement pas valable sur telephone

### ISSUE THREAD

**Issue by vikbez** [vikbez/covid-sortie#27]
[voir ce lien bfmtv](https://www.bfmtv.com/tech/confinement-finalement-l-attestation-sur-smartphone-ne-suffit-pas-1877104.html)

attendons la suite

**Comment by blipp** [comment]
Je ne suis pas juriste, le suivant est seulement mon opinion d'amateur.

Une raison forte contre une version montrée sur smartphone est qu'on pourrait la remplir vite fait quand on voit des forces d'ordre s'approcher dans la rue. Une version papier prends plus de temps à préparer et donne plus de garantie qu'on à bien réfléchi sur la nécessité de son trajet avant de partir.

Vu que la version PDF préparée par le gouvernement est un « PDF à compléter », on peut remplir ses données à l'ordinateur et l'imprimer ensuite. Donc malheureusement, cela signifie que, en ce moment, pour moi, le site web créé ici n'offre pas beaucoup plus de service aux utilisateurs. Peut-être comme proposé dans #29 il serait possible d'aider à préremplir le formulaire ou même mieux le PDF officiel.

Ceci dit, j'aime beaucoup comme ce site est réalisé techniquement (simple, local, peu de JavaScript, CSS print media target), et j'aime bien le commentaire dans le readme qui m'a en fait amené ici parce qu'une amie me demandait si tout est ok :D
```
Si vous avez des doutes pour vos données; vous pouvez demander à un ami développeur
son avis (pas de suspense, il vous dira que tout est ok)
```

**Comment by GregOriol** [comment]
France Info confirme que ce n'est plus accepté qu'en papier, imprimé ou libre : https://mobile.francetvinfo.fr/sante/maladie/coronavirus/demande-d-argent-sites-pirates-generateurs-les-arnaques-a-l-attestation-de-deplacement-pendant-l-epidemie-de-coronavirus-se-multiplient_3872927.html

**Comment by vikbez** [comment]
@blipp Merci pour les éloges :)
warnings ajoutés
