### ISSUE TITLE
Update : https://picta.fr/covid/

### ISSUE THREAD

**Issue by seyratstyle** [vikbez/covid-sortie#31]
Romain, Merci pour ton taf
Même si l'attestation sur smartphone est en stand by Possibilité d'avoir une version updaté de celle-ci aussi (MAJ footer etc...) ?! : https://picta.fr/covid/
Il se trouve que beaucoup de monde ont utilisé ce link autour de moi avant que tu sortes une nouvelle version ils se posent 
La question de savoir si c'est un fake ou non.

**Comment by vikbez** [comment]
Je ne gere pas ce site, donc je ne peux pas le mettre a jour !
Tu peux emailer l'auteur, on trouve son email sur https://picta.fr

**Comment by seyratstyle** [comment]
Merci, par contre bizarre que se soit pas géré par toi car le link github renvoie vers le tien.

**Comment by vikbez** [comment]
N'importe qui peut mettre un lien vers n'importe ou sur son site web
