### ISSUE TITLE
Téléphone & légalité

### ISSUE THREAD

**Issue by pascoual** [vikbez/covid-sortie#34]
Bonjour,
C'est diffusé par les merdias donc avec une fiabilité toute relative mais quand est-t-il du côté légal du PDF sur ton téléphone ? C'est pas vraiment un bug car on peut toujours imprimer le document sur papier.
Merci

**Comment by vikbez** [comment]
Je n'ai pas plus d'infos que ceci:

https://twitter.com/turcanmarie/status/1240223726513328130?s=21

Qui affirme donc que c'est valide et invalide a la fois.

**Comment by pascoual** [comment]
L'information sur la page https://design.numerique.gouv.fr/covid-19/ a été mise à jour avec : "Les versions numériques ne sont pas autorisées."
C'est la loose.

**Comment by vikbez** [comment]
J'ai modifié le warning (encore) pour bien préciser que c'est invalide sur telephone.
