### ISSUE TITLE
Impossible de signer sur Chrome mobile

### ISSUE THREAD

**Issue by adriencarbonne** [vikbez/covid-sortie#4]
Fonctionne parfaitement sur Firefox par contre.
Android 10.

**Comment by lasdou** [comment]
Chrome mobile impossible de signer en effet.

**Comment by japer21** [comment]
Can not sign on Google Chrome for Android. Please fix it. Otherwise, if I choose `Desktop site` then it works.

**Comment by JeanoLeBlanco** [comment]
La signature fonctionne bien lorsqu'on glisse son doigt dans le bloc correspondant (avant de cliquer sur le bouton "générer") dans Chrome mobile version 80.0.3987.132.
Avez-vous un message d'erreur ?

**Comment by japer21** [comment]
Non aucun message d'erreur... 
La version de mon Chrome: 80.0.3987.132

**Comment by Orace** [comment]
Chrome 80.0.3987.132 (Build officiel) (32 bits)
Je constate un bug lié au scroll.
La signature fonctionne bien lorsque le haut de la page est visible.
Par contre si je scroll tout en bas, il y a un offset entre la position de mon doigt et la position de la ligne.
Cela rend la zone de signature inutilisable (et sauf si on dessine très bas, on a l'impression qu'elle ne marche pas du tout).
Cet offset à l'air de correspondre au scroll.


Edit. Sur Firefox Android, en mode portrait, il n'y a pas de scroll et pas de soucis, en mode paysage il y a du scroll et la zone de signature ne marche pas du tout.

Une piste possible :
https://stackoverflow.com/a/48500289/361177

**Comment by nico62100** [comment]
Bonjour, cela fonctionne si on choisit "version pour ordinateur" dans les options de chrome.

**Comment by vikbez** [comment]
reessayez ? je viens de faire une mise a jour

**Comment by japer21** [comment]
Ça marche pour moi ! Merci
