### ISSUE TITLE
Exportation en PDF

### ISSUE THREAD

**Issue by p0lak** [vikbez/covid-sortie#5]
Bonjour, pouvez vous mettre une exportation en PDF svp?

**Comment by nico62100** [comment]
Le navigateur Chrome semble nativement proposer une impression au format pdf.

**Comment by GregOriol** [comment]
Sur iOS, il est possible de faire un PDF depuis Safari avec le bouton "partager" :
- sur d'anciennes versions, il y a une action "créer un PDF"
- sur les versions récentes, il y a une option un peu cachée : il faut faire un tap sur "Options >" qui est en bleu en haut de la fenêtre de partages, là on peut choisir PDF au lieu de Automatique, et ensuite choisir Enregistrer dans Fichiers ou l'envoyer vers une autre app (Dropbox, ...)
