### ISSUE TITLE
Cases à cocher et pas liste à puce

### ISSUE THREAD

**Issue by ragout13** [vikbez/covid-sortie#8]
Il faudrait faire des cases à cocher et non pas une liste à boutons. On peut être dehors pour plusieurs raisons donc il faudrait pouvoir cocher plusieurs cases :) Merci !!

**Comment by GregOriol** [comment]
Le document indique "au motif suivant (cocher la case)" au singulier, il ne faut donc cocher qu'une seule case; le comportement actuel semble conforme à ceci.

**Comment by vikbez** [comment]
exactement, pour l'instant je me conforme au texte, meme si le pdf du gouvernement permet de cocher plusieurs cases alors je ne sais pas trop....

**Comment by vincent-boulin** [comment]
Au pire il suffit de générer un nouveau document pour l'autre raison, ça prend 2s

**Comment by ragout13** [comment]
Malheureusement, le format digital a été invalidé par l'Etat…

**Comment by Galixte** [comment]
Je confirme: https://twitter.com/Place_Beauvau/status/1240236276416118784

**Comment by vikbez** [comment]
Apres verification, il est interdit de cocher plusieurs raisons sur le formulaire
