### ISSUE TITLE
Possibilité d'enregistrer les champs pour plusieurs utilisations

### ISSUE THREAD

**Issue by nico62100** [vikbez/covid-sortie#9]
Bonjour,
Vu que le générateur va être utilisé de nombreuses fois, est il envisageable de sauver les informations telles que nom date de naissance sur le smartphone ? 
Quand on fait "retour" après une édition pdf tout est vide. 
C'est un détail bien entendu, merci pour le développement qui va bien faciliter les choses en tout cas 😉

**Comment by vikbez** [comment]
Pour l'instant les gens flippent enormement avec leurs donnees donc je ne fais volontairement pas de local storage.
